vg_val:
  root: ${oc.env:DATA_ROOT}/vg/images
  second_root: ${oc.env:HOME}/datasets/vg/images
  ann_file: ${oc.env:HOME}/datasets/vg/annotations/val_objects.json
  coco_file: ${oc.env:HOME}/datasets/vg/annotations/val_coco.pkl
  label2ind_file: ${oc.env:HOME}/datasets/vg/annotations/vgcocooiobjects_v1_class2ind.json
  attribute2ind_file: ${oc.env:HOME}/datasets/vg/annotations/attribute2ind.json
  oid2attr_file: ${oc.env:HOME}/datasets/vg/annotations/oid2attr.json
  num_copies: 1